databases:
  - name: Blue_piggy
    databaseName: blue_piggy
    user: blue_piggy_user

services:
  - type: web
    name: blue_piggy
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blue_piggy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
